import Head from "next/head";
import { Inter } from "next/font/google";
import { getAllPosts } from "../../lib/notionAPI";
import SinglePost from "@/components/Post/SinglePost";

const inter = Inter({ subsets: ["latin"] });

// SSG - ビルドした時点でデータを取得している
// ISR - SSG もしつつ○秒ごとに更新する revalidate: 60

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();

  return {
    props: {
      // allPosts: allPosts, 1行へまとめておく
      allPosts,
    },
    revalidate: 60,
  };
};

export default function Home({ allPosts }) {
  // console.log(allPosts);
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog 🚀
        </h1>
        {allPosts.map((post) => (
          <SinglePost
            title={post.title}
            description={post.description}
            date={post.date}
            tags={post.tags}
            slug={post.slug}
          />
        ))}
      </main>
    </div>
  );
}
